add http check

diff --git a/.github/workflows/slsa-generator-nodejs-custom.yaml b/.github/workflows/slsa-generator-nodejs-custom.yaml
--- a/.github/workflows/slsa-generator-nodejs-custom.yaml
+++ b/.github/workflows/slsa-generator-nodejs-custom.yaml
@@ -127,14 +127,20 @@ jobs:
         env:
           ATTESTATION_PATH: ${{ steps.scan-attestations-signed.outputs.ATTESTATION_SIGNED_PATH }}
         run: |
-          curl -L \
-          -X POST \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/${{ github.owner }}/${{ github.repository }}/attestations \
-          -d '{"value":"{}"}'
-      - name: Upload to npmjs.com
+          response=$(curl -L \
+              -X POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/attestations \
+              -d '{"value":"{}"}' \
+              -w "%{http_code}" -o /dev/null)
+
+          if [ "$response" -ne 201 ]; then
+            echo "Error: Failed to upload attestation to GitHub API. HTTP status code: $response"
+            exit 1
+          fi
+          - name: Upload to npmjs.com
         env:
           TARBALL_PATH: ${{ steps.package-details.outputs.PACKAGE_FILENAME }}
           PROVENANCE_PATH: ${{ steps.scan-attestations-signed.outputs.ATTESTATION_SIGNED_PATH }}
